package com.waveq.app.model

import android.location.Location

/**
 * A relief shelter / safe zone the user can evacuate to.
 *
 * ## This is demo data
 *
 * Every entry in [demoSafeZones] is generated sample data for two regions
 * (Ghaziabad district in UP, and the Brahmaputra valley in Assam). The facility
 * types and localities are real place names, but the specific sites, their
 * coordinates, capacities and occupancy figures are invented. [isDemoData] is
 * true on every one of them and the UI must surface that wherever shelters are
 * listed - a shelter list that looks authoritative and is not could send someone
 * to a building that does not exist.
 *
 * Replacing this means an authority feed (SDMA / district administration) or a
 * bundled national dataset keyed by district. The shape below is what such a
 * feed would populate; nothing else needs to change.
 */
data class SafeZone(
    val id: String,
    val name: String,
    val address: String,
    val latitude: Double,
    val longitude: Double,
    val capacity: Int,
    val currentOccupancy: Int,
    val hasMedicalSupport: Boolean = true,
    val hasFoodSupplies: Boolean = true,
    val region: ShelterRegion,
    /** Always true for the bundled set. A real feed would set this false. */
    val isDemoData: Boolean = true,
) {
    /** Great-circle distance to the given point, in metres. */
    fun distanceTo(userLat: Double, userLng: Double): Float {
        val results = FloatArray(1)
        Location.distanceBetween(userLat, userLng, latitude, longitude, results)
        return results[0]
    }

    val occupancyFraction: Float
        get() = if (capacity <= 0) 0f else (currentOccupancy.toFloat() / capacity).coerceIn(0f, 1f)

    val spacesRemaining: Int get() = (capacity - currentOccupancy).coerceAtLeast(0)
}

/** The regions the bundled demo set covers. Used to say "no shelters here" honestly. */
enum class ShelterRegion(val label: String) {
    GHAZIABAD("Ghaziabad district, Uttar Pradesh"),
    ASSAM("Brahmaputra valley, Assam"),
}

/**
 * How far a shelter may be and still be offered.
 *
 * Beyond this the honest answer is "there is no shelter data for where you are",
 * not a pin 1,500 km away. The bundled set covers two regions; a user anywhere
 * else in India would otherwise have been pointed at whichever of them happened
 * to be marginally closer.
 */
const val MAX_SHELTER_DISTANCE_METERS = 150_000f

/**
 * Shelters within [MAX_SHELTER_DISTANCE_METERS] of the given point, nearest first.
 *
 * Empty when the user is outside every covered region - callers must render that
 * as "no shelters in this area" rather than falling back to the whole list.
 */
fun shelteredNear(latitude: Double, longitude: Double): List<SafeZone> =
    demoSafeZones
        .map { it to it.distanceTo(latitude, longitude) }
        .filter { (_, distance) -> distance <= MAX_SHELTER_DISTANCE_METERS }
        .sortedBy { (_, distance) -> distance }
        .map { (zone, _) -> zone }

/** Which covered region, if any, contains this point. Null when outside all of them. */
fun shelterRegionFor(latitude: Double, longitude: Double): ShelterRegion? =
    demoSafeZones
        .map { it to it.distanceTo(latitude, longitude) }
        .filter { (_, distance) -> distance <= MAX_SHELTER_DISTANCE_METERS }
        .minByOrNull { (_, distance) -> distance }
        ?.first
        ?.region

val demoSafeZones: List<SafeZone> = listOf(
    SafeZone(
        id = "GZB-01",
        name = "Vasundhara Government Inter College",
        address = "Vasundhara, Ghaziabad district, UP",
        latitude = 28.8342,
        longitude = 77.3964,
        capacity = 300,
        currentOccupancy = 25,
        hasMedicalSupport = true,
        hasFoodSupplies = true,
        region = ShelterRegion.GHAZIABAD,
    ),
    SafeZone(
        id = "GZB-02",
        name = "Indirapuram Community Centre",
        address = "Indirapuram, Ghaziabad district, UP",
        latitude = 28.5541,
        longitude = 77.5747,
        capacity = 450,
        currentOccupancy = 122,
        hasMedicalSupport = true,
        hasFoodSupplies = true,
        region = ShelterRegion.GHAZIABAD,
    ),
    SafeZone(
        id = "GZB-03",
        name = "Vaishali Sports Stadium",
        address = "Vaishali, Ghaziabad district, UP",
        latitude = 28.5999,
        longitude = 77.324,
        capacity = 200,
        currentOccupancy = 49,
        hasMedicalSupport = true,
        hasFoodSupplies = true,
        region = ShelterRegion.GHAZIABAD,
    ),
    SafeZone(
        id = "GZB-04",
        name = "Kaushambi Primary Health Centre",
        address = "Kaushambi, Ghaziabad district, UP",
        latitude = 28.5754,
        longitude = 77.414,
        capacity = 1200,
        currentOccupancy = 142,
        hasMedicalSupport = true,
        hasFoodSupplies = true,
        region = ShelterRegion.GHAZIABAD,
    ),
    SafeZone(
        id = "GZB-05",
        name = "Raj Nagar Municipal School",
        address = "Raj Nagar, Ghaziabad district, UP",
        latitude = 28.5682,
        longitude = 77.4668,
        capacity = 400,
        currentOccupancy = 140,
        hasMedicalSupport = true,
        hasFoodSupplies = true,
        region = ShelterRegion.GHAZIABAD,
    ),
    SafeZone(
        id = "GZB-06",
        name = "Kavi Nagar Higher Secondary School",
        address = "Kavi Nagar, Ghaziabad district, UP",
        latitude = 28.7277,
        longitude = 77.3574,
        capacity = 200,
        currentOccupancy = 140,
        hasMedicalSupport = true,
        hasFoodSupplies = true,
        region = ShelterRegion.GHAZIABAD,
    ),
    SafeZone(
        id = "GZB-07",
        name = "Nandgram Panchayat Bhawan",
        address = "Nandgram, Ghaziabad district, UP",
        latitude = 28.8643,
        longitude = 77.5951,
        capacity = 900,
        currentOccupancy = 416,
        hasMedicalSupport = true,
        hasFoodSupplies = true,
        region = ShelterRegion.GHAZIABAD,
    ),
    SafeZone(
        id = "GZB-08",
        name = "Loni Government Degree College",
        address = "Loni, Ghaziabad district, UP",
        latitude = 28.8559,
        longitude = 77.3464,
        capacity = 200,
        currentOccupancy = 48,
        hasMedicalSupport = true,
        hasFoodSupplies = true,
        region = ShelterRegion.GHAZIABAD,
    ),
    SafeZone(
        id = "GZB-09",
        name = "Muradnagar Town Hall",
        address = "Muradnagar, Ghaziabad district, UP",
        latitude = 28.8304,
        longitude = 77.5202,
        capacity = 600,
        currentOccupancy = 415,
        hasMedicalSupport = true,
        hasFoodSupplies = false,
        region = ShelterRegion.GHAZIABAD,
    ),
    SafeZone(
        id = "GZB-10",
        name = "Modinagar District Sports Complex",
        address = "Modinagar, Ghaziabad district, UP",
        latitude = 28.8223,
        longitude = 77.3125,
        capacity = 300,
        currentOccupancy = 196,
        hasMedicalSupport = true,
        hasFoodSupplies = true,
        region = ShelterRegion.GHAZIABAD,
    ),
    SafeZone(
        id = "GZB-11",
        name = "Dasna Government Inter College",
        address = "Dasna, Ghaziabad district, UP",
        latitude = 28.7769,
        longitude = 77.472,
        capacity = 300,
        currentOccupancy = 65,
        hasMedicalSupport = false,
        hasFoodSupplies = true,
        region = ShelterRegion.GHAZIABAD,
    ),
    SafeZone(
        id = "GZB-12",
        name = "Masuri Community Centre",
        address = "Masuri, Ghaziabad district, UP",
        latitude = 28.7595,
        longitude = 77.3654,
        capacity = 750,
        currentOccupancy = 568,
        hasMedicalSupport = true,
        hasFoodSupplies = true,
        region = ShelterRegion.GHAZIABAD,
    ),
    SafeZone(
        id = "GZB-13",
        name = "Bhojpur Sports Stadium",
        address = "Bhojpur, Ghaziabad district, UP",
        latitude = 28.6115,
        longitude = 77.4374,
        capacity = 1200,
        currentOccupancy = 120,
        hasMedicalSupport = true,
        hasFoodSupplies = false,
        region = ShelterRegion.GHAZIABAD,
    ),
    SafeZone(
        id = "GZB-14",
        name = "Sahibabad Primary Health Centre",
        address = "Sahibabad, Ghaziabad district, UP",
        latitude = 28.8561,
        longitude = 77.2966,
        capacity = 1200,
        currentOccupancy = 61,
        hasMedicalSupport = false,
        hasFoodSupplies = true,
        region = ShelterRegion.GHAZIABAD,
    ),
    SafeZone(
        id = "GZB-15",
        name = "Govindpuram Municipal School",
        address = "Govindpuram, Ghaziabad district, UP",
        latitude = 28.6047,
        longitude = 77.4675,
        capacity = 1200,
        currentOccupancy = 1007,
        hasMedicalSupport = false,
        hasFoodSupplies = true,
        region = ShelterRegion.GHAZIABAD,
    ),
    SafeZone(
        id = "GZB-16",
        name = "Shastri Nagar Higher Secondary School",
        address = "Shastri Nagar, Ghaziabad district, UP",
        latitude = 28.5863,
        longitude = 77.6292,
        capacity = 300,
        currentOccupancy = 134,
        hasMedicalSupport = true,
        hasFoodSupplies = true,
        region = ShelterRegion.GHAZIABAD,
    ),
    SafeZone(
        id = "GZB-17",
        name = "Patel Nagar Panchayat Bhawan",
        address = "Patel Nagar, Ghaziabad district, UP",
        latitude = 28.7841,
        longitude = 77.3445,
        capacity = 200,
        currentOccupancy = 169,
        hasMedicalSupport = true,
        hasFoodSupplies = false,
        region = ShelterRegion.GHAZIABAD,
    ),
    SafeZone(
        id = "GZB-18",
        name = "Nehru Nagar Government Degree College",
        address = "Nehru Nagar, Ghaziabad district, UP",
        latitude = 28.7302,
        longitude = 77.469,
        capacity = 200,
        currentOccupancy = 181,
        hasMedicalSupport = true,
        hasFoodSupplies = false,
        region = ShelterRegion.GHAZIABAD,
    ),
    SafeZone(
        id = "GZB-19",
        name = "Crossings Republik Town Hall",
        address = "Crossings Republik, Ghaziabad district, UP",
        latitude = 28.766,
        longitude = 77.4182,
        capacity = 750,
        currentOccupancy = 581,
        hasMedicalSupport = true,
        hasFoodSupplies = true,
        region = ShelterRegion.GHAZIABAD,
    ),
    SafeZone(
        id = "GZB-20",
        name = "Sihani Gate District Sports Complex",
        address = "Sihani Gate, Ghaziabad district, UP",
        latitude = 28.5657,
        longitude = 77.3614,
        capacity = 450,
        currentOccupancy = 136,
        hasMedicalSupport = false,
        hasFoodSupplies = true,
        region = ShelterRegion.GHAZIABAD,
    ),
    SafeZone(
        id = "GZB-21",
        name = "Lal Kuan Government Inter College",
        address = "Lal Kuan, Ghaziabad district, UP",
        latitude = 28.6265,
        longitude = 77.3866,
        capacity = 900,
        currentOccupancy = 361,
        hasMedicalSupport = true,
        hasFoodSupplies = true,
        region = ShelterRegion.GHAZIABAD,
    ),
    SafeZone(
        id = "GZB-22",
        name = "Arthala Community Centre",
        address = "Arthala, Ghaziabad district, UP",
        latitude = 28.7461,
        longitude = 77.452,
        capacity = 200,
        currentOccupancy = 113,
        hasMedicalSupport = true,
        hasFoodSupplies = true,
        region = ShelterRegion.GHAZIABAD,
    ),
    SafeZone(
        id = "GZB-23",
        name = "Mohan Nagar Sports Stadium",
        address = "Mohan Nagar, Ghaziabad district, UP",
        latitude = 28.5671,
        longitude = 77.2945,
        capacity = 1200,
        currentOccupancy = 930,
        hasMedicalSupport = true,
        hasFoodSupplies = true,
        region = ShelterRegion.GHAZIABAD,
    ),
    SafeZone(
        id = "GZB-24",
        name = "Pratap Vihar Primary Health Centre",
        address = "Pratap Vihar, Ghaziabad district, UP",
        latitude = 28.6719,
        longitude = 77.3719,
        capacity = 1500,
        currentOccupancy = 1112,
        hasMedicalSupport = true,
        hasFoodSupplies = true,
        region = ShelterRegion.GHAZIABAD,
    ),
    SafeZone(
        id = "GZB-25",
        name = "Kamla Nehru Nagar Municipal School",
        address = "Kamla Nehru Nagar, Ghaziabad district, UP",
        latitude = 28.8171,
        longitude = 77.5848,
        capacity = 400,
        currentOccupancy = 265,
        hasMedicalSupport = true,
        hasFoodSupplies = true,
        region = ShelterRegion.GHAZIABAD,
    ),
    SafeZone(
        id = "GZB-26",
        name = "Vasundhara Higher Secondary School",
        address = "Vasundhara, Ghaziabad district, UP",
        latitude = 28.6958,
        longitude = 77.4492,
        capacity = 400,
        currentOccupancy = 290,
        hasMedicalSupport = true,
        hasFoodSupplies = true,
        region = ShelterRegion.GHAZIABAD,
    ),
    SafeZone(
        id = "GZB-27",
        name = "Indirapuram Panchayat Bhawan",
        address = "Indirapuram, Ghaziabad district, UP",
        latitude = 28.8104,
        longitude = 77.351,
        capacity = 200,
        currentOccupancy = 111,
        hasMedicalSupport = false,
        hasFoodSupplies = true,
        region = ShelterRegion.GHAZIABAD,
    ),
    SafeZone(
        id = "GZB-28",
        name = "Vaishali Government Degree College",
        address = "Vaishali, Ghaziabad district, UP",
        latitude = 28.7074,
        longitude = 77.3828,
        capacity = 400,
        currentOccupancy = 48,
        hasMedicalSupport = true,
        hasFoodSupplies = true,
        region = ShelterRegion.GHAZIABAD,
    ),
    SafeZone(
        id = "GZB-29",
        name = "Kaushambi Town Hall",
        address = "Kaushambi, Ghaziabad district, UP",
        latitude = 28.744,
        longitude = 77.5719,
        capacity = 400,
        currentOccupancy = 157,
        hasMedicalSupport = false,
        hasFoodSupplies = false,
        region = ShelterRegion.GHAZIABAD,
    ),
    SafeZone(
        id = "GZB-30",
        name = "Raj Nagar District Sports Complex",
        address = "Raj Nagar, Ghaziabad district, UP",
        latitude = 28.7781,
        longitude = 77.4494,
        capacity = 1500,
        currentOccupancy = 1246,
        hasMedicalSupport = true,
        hasFoodSupplies = true,
        region = ShelterRegion.GHAZIABAD,
    ),
    SafeZone(
        id = "GZB-31",
        name = "Kavi Nagar Government Inter College",
        address = "Kavi Nagar, Ghaziabad district, UP",
        latitude = 28.7053,
        longitude = 77.5538,
        capacity = 900,
        currentOccupancy = 684,
        hasMedicalSupport = true,
        hasFoodSupplies = true,
        region = ShelterRegion.GHAZIABAD,
    ),
    SafeZone(
        id = "GZB-32",
        name = "Nandgram Community Centre",
        address = "Nandgram, Ghaziabad district, UP",
        latitude = 28.7238,
        longitude = 77.2864,
        capacity = 600,
        currentOccupancy = 468,
        hasMedicalSupport = true,
        hasFoodSupplies = false,
        region = ShelterRegion.GHAZIABAD,
    ),
    SafeZone(
        id = "GZB-33",
        name = "Loni Sports Stadium",
        address = "Loni, Ghaziabad district, UP",
        latitude = 28.6974,
        longitude = 77.6331,
        capacity = 450,
        currentOccupancy = 313,
        hasMedicalSupport = false,
        hasFoodSupplies = true,
        region = ShelterRegion.GHAZIABAD,
    ),
    SafeZone(
        id = "GZB-34",
        name = "Muradnagar Primary Health Centre",
        address = "Muradnagar, Ghaziabad district, UP",
        latitude = 28.7556,
        longitude = 77.6189,
        capacity = 600,
        currentOccupancy = 452,
        hasMedicalSupport = false,
        hasFoodSupplies = true,
        region = ShelterRegion.GHAZIABAD,
    ),
    SafeZone(
        id = "GZB-35",
        name = "Modinagar Municipal School",
        address = "Modinagar, Ghaziabad district, UP",
        latitude = 28.7572,
        longitude = 77.3723,
        capacity = 1200,
        currentOccupancy = 678,
        hasMedicalSupport = false,
        hasFoodSupplies = true,
        region = ShelterRegion.GHAZIABAD,
    ),
    SafeZone(
        id = "GZB-36",
        name = "Dasna Higher Secondary School",
        address = "Dasna, Ghaziabad district, UP",
        latitude = 28.6918,
        longitude = 77.5246,
        capacity = 200,
        currentOccupancy = 147,
        hasMedicalSupport = true,
        hasFoodSupplies = false,
        region = ShelterRegion.GHAZIABAD,
    ),
    SafeZone(
        id = "GZB-37",
        name = "Masuri Panchayat Bhawan",
        address = "Masuri, Ghaziabad district, UP",
        latitude = 28.6465,
        longitude = 77.6045,
        capacity = 450,
        currentOccupancy = 338,
        hasMedicalSupport = true,
        hasFoodSupplies = true,
        region = ShelterRegion.GHAZIABAD,
    ),
    SafeZone(
        id = "GZB-38",
        name = "Bhojpur Government Degree College",
        address = "Bhojpur, Ghaziabad district, UP",
        latitude = 28.7332,
        longitude = 77.4599,
        capacity = 450,
        currentOccupancy = 332,
        hasMedicalSupport = true,
        hasFoodSupplies = true,
        region = ShelterRegion.GHAZIABAD,
    ),
    SafeZone(
        id = "GZB-39",
        name = "Sahibabad Town Hall",
        address = "Sahibabad, Ghaziabad district, UP",
        latitude = 28.8551,
        longitude = 77.4,
        capacity = 450,
        currentOccupancy = 64,
        hasMedicalSupport = true,
        hasFoodSupplies = false,
        region = ShelterRegion.GHAZIABAD,
    ),
    SafeZone(
        id = "GZB-40",
        name = "Govindpuram District Sports Complex",
        address = "Govindpuram, Ghaziabad district, UP",
        latitude = 28.594,
        longitude = 77.3926,
        capacity = 200,
        currentOccupancy = 45,
        hasMedicalSupport = true,
        hasFoodSupplies = true,
        region = ShelterRegion.GHAZIABAD,
    ),
    SafeZone(
        id = "GZB-41",
        name = "Shastri Nagar Government Inter College",
        address = "Shastri Nagar, Ghaziabad district, UP",
        latitude = 28.6346,
        longitude = 77.3693,
        capacity = 1200,
        currentOccupancy = 625,
        hasMedicalSupport = true,
        hasFoodSupplies = true,
        region = ShelterRegion.GHAZIABAD,
    ),
    SafeZone(
        id = "GZB-42",
        name = "Patel Nagar Community Centre",
        address = "Patel Nagar, Ghaziabad district, UP",
        latitude = 28.8336,
        longitude = 77.5552,
        capacity = 750,
        currentOccupancy = 659,
        hasMedicalSupport = true,
        hasFoodSupplies = true,
        region = ShelterRegion.GHAZIABAD,
    ),
    SafeZone(
        id = "GZB-43",
        name = "Nehru Nagar Sports Stadium",
        address = "Nehru Nagar, Ghaziabad district, UP",
        latitude = 28.5665,
        longitude = 77.5712,
        capacity = 1500,
        currentOccupancy = 283,
        hasMedicalSupport = true,
        hasFoodSupplies = true,
        region = ShelterRegion.GHAZIABAD,
    ),
    SafeZone(
        id = "GZB-44",
        name = "Crossings Republik Primary Health Centre",
        address = "Crossings Republik, Ghaziabad district, UP",
        latitude = 28.7247,
        longitude = 77.6129,
        capacity = 1500,
        currentOccupancy = 589,
        hasMedicalSupport = true,
        hasFoodSupplies = true,
        region = ShelterRegion.GHAZIABAD,
    ),
    SafeZone(
        id = "GZB-45",
        name = "Sihani Gate Municipal School",
        address = "Sihani Gate, Ghaziabad district, UP",
        latitude = 28.6349,
        longitude = 77.4827,
        capacity = 400,
        currentOccupancy = 41,
        hasMedicalSupport = true,
        hasFoodSupplies = true,
        region = ShelterRegion.GHAZIABAD,
    ),
    SafeZone(
        id = "GZB-46",
        name = "Lal Kuan Higher Secondary School",
        address = "Lal Kuan, Ghaziabad district, UP",
        latitude = 28.6113,
        longitude = 77.4392,
        capacity = 200,
        currentOccupancy = 95,
        hasMedicalSupport = false,
        hasFoodSupplies = true,
        region = ShelterRegion.GHAZIABAD,
    ),
    SafeZone(
        id = "GZB-47",
        name = "Arthala Panchayat Bhawan",
        address = "Arthala, Ghaziabad district, UP",
        latitude = 28.8526,
        longitude = 77.3602,
        capacity = 900,
        currentOccupancy = 120,
        hasMedicalSupport = true,
        hasFoodSupplies = true,
        region = ShelterRegion.GHAZIABAD,
    ),
    SafeZone(
        id = "GZB-48",
        name = "Mohan Nagar Government Degree College",
        address = "Mohan Nagar, Ghaziabad district, UP",
        latitude = 28.858,
        longitude = 77.345,
        capacity = 600,
        currentOccupancy = 526,
        hasMedicalSupport = true,
        hasFoodSupplies = true,
        region = ShelterRegion.GHAZIABAD,
    ),
    SafeZone(
        id = "GZB-49",
        name = "Pratap Vihar Town Hall",
        address = "Pratap Vihar, Ghaziabad district, UP",
        latitude = 28.7008,
        longitude = 77.4633,
        capacity = 1500,
        currentOccupancy = 920,
        hasMedicalSupport = true,
        hasFoodSupplies = true,
        region = ShelterRegion.GHAZIABAD,
    ),
    SafeZone(
        id = "GZB-50",
        name = "Kamla Nehru Nagar District Sports Complex",
        address = "Kamla Nehru Nagar, Ghaziabad district, UP",
        latitude = 28.668,
        longitude = 77.4956,
        capacity = 750,
        currentOccupancy = 309,
        hasMedicalSupport = true,
        hasFoodSupplies = true,
        region = ShelterRegion.GHAZIABAD,
    ),
    SafeZone(
        id = "ASM-01",
        name = "Dispur Government Inter College",
        address = "Dispur, Assam",
        latitude = 25.8606,
        longitude = 93.1683,
        capacity = 900,
        currentOccupancy = 773,
        hasMedicalSupport = true,
        hasFoodSupplies = true,
        region = ShelterRegion.ASSAM,
    ),
    SafeZone(
        id = "ASM-02",
        name = "Beltola Community Centre",
        address = "Beltola, Assam",
        latitude = 27.1367,
        longitude = 93.7525,
        capacity = 450,
        currentOccupancy = 150,
        hasMedicalSupport = false,
        hasFoodSupplies = true,
        region = ShelterRegion.ASSAM,
    ),
    SafeZone(
        id = "ASM-03",
        name = "Jalukbari Sports Stadium",
        address = "Jalukbari, Assam",
        latitude = 25.8157,
        longitude = 91.4501,
        capacity = 300,
        currentOccupancy = 208,
        hasMedicalSupport = true,
        hasFoodSupplies = true,
        region = ShelterRegion.ASSAM,
    ),
    SafeZone(
        id = "ASM-04",
        name = "Maligaon Primary Health Centre",
        address = "Maligaon, Assam",
        latitude = 26.025,
        longitude = 91.7232,
        capacity = 400,
        currentOccupancy = 279,
        hasMedicalSupport = false,
        hasFoodSupplies = false,
        region = ShelterRegion.ASSAM,
    ),
    SafeZone(
        id = "ASM-05",
        name = "Chandmari Municipal School",
        address = "Chandmari, Assam",
        latitude = 25.6988,
        longitude = 90.794,
        capacity = 300,
        currentOccupancy = 259,
        hasMedicalSupport = true,
        hasFoodSupplies = true,
        region = ShelterRegion.ASSAM,
    ),
    SafeZone(
        id = "ASM-06",
        name = "Barpeta Higher Secondary School",
        address = "Barpeta, Assam",
        latitude = 27.0567,
        longitude = 92.4947,
        capacity = 300,
        currentOccupancy = 37,
        hasMedicalSupport = false,
        hasFoodSupplies = true,
        region = ShelterRegion.ASSAM,
    ),
    SafeZone(
        id = "ASM-07",
        name = "Dhubri Panchayat Bhawan",
        address = "Dhubri, Assam",
        latitude = 25.8257,
        longitude = 90.5722,
        capacity = 1500,
        currentOccupancy = 755,
        hasMedicalSupport = true,
        hasFoodSupplies = true,
        region = ShelterRegion.ASSAM,
    ),
    SafeZone(
        id = "ASM-08",
        name = "Goalpara Government Degree College",
        address = "Goalpara, Assam",
        latitude = 26.3412,
        longitude = 90.5233,
        capacity = 900,
        currentOccupancy = 219,
        hasMedicalSupport = true,
        hasFoodSupplies = true,
        region = ShelterRegion.ASSAM,
    ),
    SafeZone(
        id = "ASM-09",
        name = "Morigaon Town Hall",
        address = "Morigaon, Assam",
        latitude = 26.434,
        longitude = 95.1658,
        capacity = 450,
        currentOccupancy = 70,
        hasMedicalSupport = true,
        hasFoodSupplies = true,
        region = ShelterRegion.ASSAM,
    ),
    SafeZone(
        id = "ASM-10",
        name = "Nagaon District Sports Complex",
        address = "Nagaon, Assam",
        latitude = 26.7606,
        longitude = 94.6312,
        capacity = 1500,
        currentOccupancy = 925,
        hasMedicalSupport = true,
        hasFoodSupplies = true,
        region = ShelterRegion.ASSAM,
    ),
    SafeZone(
        id = "ASM-11",
        name = "Jorhat Government Inter College",
        address = "Jorhat, Assam",
        latitude = 27.154,
        longitude = 90.604,
        capacity = 400,
        currentOccupancy = 235,
        hasMedicalSupport = true,
        hasFoodSupplies = true,
        region = ShelterRegion.ASSAM,
    ),
    SafeZone(
        id = "ASM-12",
        name = "Dibrugarh Community Centre",
        address = "Dibrugarh, Assam",
        latitude = 25.9771,
        longitude = 94.8574,
        capacity = 1500,
        currentOccupancy = 489,
        hasMedicalSupport = true,
        hasFoodSupplies = false,
        region = ShelterRegion.ASSAM,
    ),
    SafeZone(
        id = "ASM-13",
        name = "Sivasagar Sports Stadium",
        address = "Sivasagar, Assam",
        latitude = 25.0212,
        longitude = 92.6055,
        capacity = 200,
        currentOccupancy = 153,
        hasMedicalSupport = false,
        hasFoodSupplies = false,
        region = ShelterRegion.ASSAM,
    ),
    SafeZone(
        id = "ASM-14",
        name = "Tinsukia Primary Health Centre",
        address = "Tinsukia, Assam",
        latitude = 27.405,
        longitude = 93.5845,
        capacity = 300,
        currentOccupancy = 103,
        hasMedicalSupport = true,
        hasFoodSupplies = true,
        region = ShelterRegion.ASSAM,
    ),
    SafeZone(
        id = "ASM-15",
        name = "North Lakhimpur Municipal School",
        address = "North Lakhimpur, Assam",
        latitude = 27.0151,
        longitude = 90.9652,
        capacity = 1500,
        currentOccupancy = 522,
        hasMedicalSupport = false,
        hasFoodSupplies = false,
        region = ShelterRegion.ASSAM,
    ),
    SafeZone(
        id = "ASM-16",
        name = "Dhemaji Higher Secondary School",
        address = "Dhemaji, Assam",
        latitude = 26.0568,
        longitude = 92.8857,
        capacity = 900,
        currentOccupancy = 475,
        hasMedicalSupport = true,
        hasFoodSupplies = true,
        region = ShelterRegion.ASSAM,
    ),
    SafeZone(
        id = "ASM-17",
        name = "Golaghat Panchayat Bhawan",
        address = "Golaghat, Assam",
        latitude = 25.944,
        longitude = 94.0506,
        capacity = 300,
        currentOccupancy = 56,
        hasMedicalSupport = true,
        hasFoodSupplies = true,
        region = ShelterRegion.ASSAM,
    ),
    SafeZone(
        id = "ASM-18",
        name = "Tezpur Government Degree College",
        address = "Tezpur, Assam",
        latitude = 24.9697,
        longitude = 90.5336,
        capacity = 1200,
        currentOccupancy = 823,
        hasMedicalSupport = false,
        hasFoodSupplies = true,
        region = ShelterRegion.ASSAM,
    ),
    SafeZone(
        id = "ASM-19",
        name = "Silchar Town Hall",
        address = "Silchar, Assam",
        latitude = 26.438,
        longitude = 92.8327,
        capacity = 1200,
        currentOccupancy = 537,
        hasMedicalSupport = true,
        hasFoodSupplies = true,
        region = ShelterRegion.ASSAM,
    ),
    SafeZone(
        id = "ASM-20",
        name = "Karimganj District Sports Complex",
        address = "Karimganj, Assam",
        latitude = 25.2528,
        longitude = 91.7701,
        capacity = 1200,
        currentOccupancy = 349,
        hasMedicalSupport = false,
        hasFoodSupplies = true,
        region = ShelterRegion.ASSAM,
    ),
    SafeZone(
        id = "ASM-21",
        name = "Hailakandi Government Inter College",
        address = "Hailakandi, Assam",
        latitude = 26.7955,
        longitude = 89.8086,
        capacity = 900,
        currentOccupancy = 273,
        hasMedicalSupport = true,
        hasFoodSupplies = true,
        region = ShelterRegion.ASSAM,
    ),
    SafeZone(
        id = "ASM-22",
        name = "Bongaigaon Community Centre",
        address = "Bongaigaon, Assam",
        latitude = 26.3153,
        longitude = 92.1174,
        capacity = 900,
        currentOccupancy = 597,
        hasMedicalSupport = true,
        hasFoodSupplies = false,
        region = ShelterRegion.ASSAM,
    ),
    SafeZone(
        id = "ASM-23",
        name = "Nalbari Sports Stadium",
        address = "Nalbari, Assam",
        latitude = 25.1139,
        longitude = 94.359,
        capacity = 400,
        currentOccupancy = 141,
        hasMedicalSupport = true,
        hasFoodSupplies = true,
        region = ShelterRegion.ASSAM,
    ),
    SafeZone(
        id = "ASM-24",
        name = "Kokrajhar Primary Health Centre",
        address = "Kokrajhar, Assam",
        latitude = 25.0246,
        longitude = 92.2969,
        capacity = 600,
        currentOccupancy = 113,
        hasMedicalSupport = true,
        hasFoodSupplies = true,
        region = ShelterRegion.ASSAM,
    ),
    SafeZone(
        id = "ASM-25",
        name = "Rangia Municipal School",
        address = "Rangia, Assam",
        latitude = 26.4678,
        longitude = 90.059,
        capacity = 300,
        currentOccupancy = 21,
        hasMedicalSupport = true,
        hasFoodSupplies = true,
        region = ShelterRegion.ASSAM,
    ),
    SafeZone(
        id = "ASM-26",
        name = "Dispur Higher Secondary School",
        address = "Dispur, Assam",
        latitude = 25.8488,
        longitude = 90.7063,
        capacity = 600,
        currentOccupancy = 162,
        hasMedicalSupport = true,
        hasFoodSupplies = true,
        region = ShelterRegion.ASSAM,
    ),
    SafeZone(
        id = "ASM-27",
        name = "Beltola Panchayat Bhawan",
        address = "Beltola, Assam",
        latitude = 26.5063,
        longitude = 95.1648,
        capacity = 600,
        currentOccupancy = 459,
        hasMedicalSupport = true,
        hasFoodSupplies = true,
        region = ShelterRegion.ASSAM,
    ),
    SafeZone(
        id = "ASM-28",
        name = "Jalukbari Government Degree College",
        address = "Jalukbari, Assam",
        latitude = 26.7397,
        longitude = 92.3871,
        capacity = 1200,
        currentOccupancy = 283,
        hasMedicalSupport = true,
        hasFoodSupplies = true,
        region = ShelterRegion.ASSAM,
    ),
    SafeZone(
        id = "ASM-29",
        name = "Maligaon Town Hall",
        address = "Maligaon, Assam",
        latitude = 26.7671,
        longitude = 92.2339,
        capacity = 300,
        currentOccupancy = 251,
        hasMedicalSupport = true,
        hasFoodSupplies = true,
        region = ShelterRegion.ASSAM,
    ),
    SafeZone(
        id = "ASM-30",
        name = "Chandmari District Sports Complex",
        address = "Chandmari, Assam",
        latitude = 27.3234,
        longitude = 91.4427,
        capacity = 450,
        currentOccupancy = 93,
        hasMedicalSupport = true,
        hasFoodSupplies = true,
        region = ShelterRegion.ASSAM,
    ),
    SafeZone(
        id = "ASM-31",
        name = "Barpeta Government Inter College",
        address = "Barpeta, Assam",
        latitude = 25.5219,
        longitude = 89.8622,
        capacity = 400,
        currentOccupancy = 274,
        hasMedicalSupport = true,
        hasFoodSupplies = true,
        region = ShelterRegion.ASSAM,
    ),
    SafeZone(
        id = "ASM-32",
        name = "Dhubri Community Centre",
        address = "Dhubri, Assam",
        latitude = 25.2062,
        longitude = 95.1472,
        capacity = 300,
        currentOccupancy = 69,
        hasMedicalSupport = true,
        hasFoodSupplies = true,
        region = ShelterRegion.ASSAM,
    ),
    SafeZone(
        id = "ASM-33",
        name = "Goalpara Sports Stadium",
        address = "Goalpara, Assam",
        latitude = 25.0428,
        longitude = 94.8623,
        capacity = 600,
        currentOccupancy = 307,
        hasMedicalSupport = true,
        hasFoodSupplies = true,
        region = ShelterRegion.ASSAM,
    ),
    SafeZone(
        id = "ASM-34",
        name = "Morigaon Primary Health Centre",
        address = "Morigaon, Assam",
        latitude = 24.901,
        longitude = 94.3421,
        capacity = 200,
        currentOccupancy = 92,
        hasMedicalSupport = true,
        hasFoodSupplies = true,
        region = ShelterRegion.ASSAM,
    ),
    SafeZone(
        id = "ASM-35",
        name = "Nagaon Municipal School",
        address = "Nagaon, Assam",
        latitude = 25.3803,
        longitude = 91.6865,
        capacity = 200,
        currentOccupancy = 114,
        hasMedicalSupport = true,
        hasFoodSupplies = true,
        region = ShelterRegion.ASSAM,
    ),
    SafeZone(
        id = "ASM-36",
        name = "Jorhat Higher Secondary School",
        address = "Jorhat, Assam",
        latitude = 25.3352,
        longitude = 90.4212,
        capacity = 300,
        currentOccupancy = 19,
        hasMedicalSupport = true,
        hasFoodSupplies = true,
        region = ShelterRegion.ASSAM,
    ),
    SafeZone(
        id = "ASM-37",
        name = "Dibrugarh Panchayat Bhawan",
        address = "Dibrugarh, Assam",
        latitude = 27.0622,
        longitude = 91.5908,
        capacity = 1500,
        currentOccupancy = 139,
        hasMedicalSupport = false,
        hasFoodSupplies = false,
        region = ShelterRegion.ASSAM,
    ),
    SafeZone(
        id = "ASM-38",
        name = "Sivasagar Government Degree College",
        address = "Sivasagar, Assam",
        latitude = 25.2284,
        longitude = 93.7214,
        capacity = 750,
        currentOccupancy = 520,
        hasMedicalSupport = true,
        hasFoodSupplies = true,
        region = ShelterRegion.ASSAM,
    ),
    SafeZone(
        id = "ASM-39",
        name = "Tinsukia Town Hall",
        address = "Tinsukia, Assam",
        latitude = 25.9371,
        longitude = 90.3309,
        capacity = 750,
        currentOccupancy = 451,
        hasMedicalSupport = true,
        hasFoodSupplies = true,
        region = ShelterRegion.ASSAM,
    ),
    SafeZone(
        id = "ASM-40",
        name = "North Lakhimpur District Sports Complex",
        address = "North Lakhimpur, Assam",
        latitude = 27.2011,
        longitude = 91.1317,
        capacity = 750,
        currentOccupancy = 324,
        hasMedicalSupport = true,
        hasFoodSupplies = true,
        region = ShelterRegion.ASSAM,
    ),
    SafeZone(
        id = "ASM-41",
        name = "Dhemaji Government Inter College",
        address = "Dhemaji, Assam",
        latitude = 27.0613,
        longitude = 93.6301,
        capacity = 900,
        currentOccupancy = 180,
        hasMedicalSupport = true,
        hasFoodSupplies = true,
        region = ShelterRegion.ASSAM,
    ),
    SafeZone(
        id = "ASM-42",
        name = "Golaghat Community Centre",
        address = "Golaghat, Assam",
        latitude = 27.1245,
        longitude = 91.4019,
        capacity = 400,
        currentOccupancy = 216,
        hasMedicalSupport = true,
        hasFoodSupplies = true,
        region = ShelterRegion.ASSAM,
    ),
    SafeZone(
        id = "ASM-43",
        name = "Tezpur Sports Stadium",
        address = "Tezpur, Assam",
        latitude = 26.7275,
        longitude = 93.6559,
        capacity = 400,
        currentOccupancy = 96,
        hasMedicalSupport = true,
        hasFoodSupplies = true,
        region = ShelterRegion.ASSAM,
    ),
    SafeZone(
        id = "ASM-44",
        name = "Silchar Primary Health Centre",
        address = "Silchar, Assam",
        latitude = 24.9776,
        longitude = 91.1669,
        capacity = 900,
        currentOccupancy = 323,
        hasMedicalSupport = false,
        hasFoodSupplies = true,
        region = ShelterRegion.ASSAM,
    ),
    SafeZone(
        id = "ASM-45",
        name = "Karimganj Municipal School",
        address = "Karimganj, Assam",
        latitude = 25.0539,
        longitude = 93.4814,
        capacity = 900,
        currentOccupancy = 211,
        hasMedicalSupport = true,
        hasFoodSupplies = true,
        region = ShelterRegion.ASSAM,
    ),
    SafeZone(
        id = "ASM-46",
        name = "Hailakandi Higher Secondary School",
        address = "Hailakandi, Assam",
        latitude = 25.978,
        longitude = 94.1542,
        capacity = 400,
        currentOccupancy = 176,
        hasMedicalSupport = true,
        hasFoodSupplies = true,
        region = ShelterRegion.ASSAM,
    ),
    SafeZone(
        id = "ASM-47",
        name = "Bongaigaon Panchayat Bhawan",
        address = "Bongaigaon, Assam",
        latitude = 26.8824,
        longitude = 90.5904,
        capacity = 1200,
        currentOccupancy = 636,
        hasMedicalSupport = true,
        hasFoodSupplies = true,
        region = ShelterRegion.ASSAM,
    ),
    SafeZone(
        id = "ASM-48",
        name = "Nalbari Government Degree College",
        address = "Nalbari, Assam",
        latitude = 24.9935,
        longitude = 94.3277,
        capacity = 600,
        currentOccupancy = 422,
        hasMedicalSupport = true,
        hasFoodSupplies = true,
        region = ShelterRegion.ASSAM,
    ),
    SafeZone(
        id = "ASM-49",
        name = "Kokrajhar Town Hall",
        address = "Kokrajhar, Assam",
        latitude = 25.6201,
        longitude = 94.5674,
        capacity = 600,
        currentOccupancy = 320,
        hasMedicalSupport = true,
        hasFoodSupplies = false,
        region = ShelterRegion.ASSAM,
    ),
    SafeZone(
        id = "ASM-50",
        name = "Rangia District Sports Complex",
        address = "Rangia, Assam",
        latitude = 26.3531,
        longitude = 90.3998,
        capacity = 1500,
        currentOccupancy = 1030,
        hasMedicalSupport = true,
        hasFoodSupplies = true,
        region = ShelterRegion.ASSAM,
    ),
)
